// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: proto/metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricServer_PushProtoMetrics_FullMethodName = "/metrics.MetricServer/PushProtoMetrics"
)

// MetricServerClient is the client API for MetricServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricServerClient interface {
	PushProtoMetrics(ctx context.Context, in *PushProtoMetricsRequest, opts ...grpc.CallOption) (*PushProtoMetricsResponse, error)
}

type metricServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricServerClient(cc grpc.ClientConnInterface) MetricServerClient {
	return &metricServerClient{cc}
}

func (c *metricServerClient) PushProtoMetrics(ctx context.Context, in *PushProtoMetricsRequest, opts ...grpc.CallOption) (*PushProtoMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{}, opts...)
	out := new(PushProtoMetricsResponse)
	err := c.cc.Invoke(ctx, MetricServer_PushProtoMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricServerServer is the server API for MetricServer service.
// All implementations must embed UnimplementedMetricServerServer
// for forward compatibility.
type MetricServerServer interface {
	PushProtoMetrics(context.Context, *PushProtoMetricsRequest) (*PushProtoMetricsResponse, error)
	mustEmbedUnimplementedMetricServerServer()
}

// UnimplementedMetricServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricServerServer struct{}

func (UnimplementedMetricServerServer) PushProtoMetrics(context.Context, *PushProtoMetricsRequest) (*PushProtoMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushProtoMetrics not implemented")
}
func (UnimplementedMetricServerServer) mustEmbedUnimplementedMetricServerServer() {}
func (UnimplementedMetricServerServer) testEmbeddedByValue()                      {}

// UnsafeMetricServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricServerServer will
// result in compilation errors.
type UnsafeMetricServerServer interface {
	mustEmbedUnimplementedMetricServerServer()
}

func RegisterMetricServerServer(s grpc.ServiceRegistrar, srv MetricServerServer) {
	// If the following call pancis, it indicates UnimplementedMetricServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricServer_ServiceDesc, srv)
}

func _MetricServer_PushProtoMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushProtoMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricServerServer).PushProtoMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricServer_PushProtoMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricServerServer).PushProtoMetrics(ctx, req.(*PushProtoMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricServer_ServiceDesc is the grpc.ServiceDesc for MetricServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricServer",
	HandlerType: (*MetricServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushProtoMetrics",
			Handler:    _MetricServer_PushProtoMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metrics.proto",
}
